services:
  - type: web
    name: snapstudy-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Other environment variables (MONGODB_URI, JWT_SECRET, API keys, etc.) 
    # will be added manually in Render dashboard for security